#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and set up Nginx

apt-get update -y
apt-get install -y nginx

service nginx start

sed -i '/^listen\s\+80;/c\listen 80;' /etc/nginx/sites-available/default

kill -HUP "$(cat /var/run/nginx.pid)"

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
