#!/usr/bin/env bash
# Installs and configures Nginx on an Ubuntu machine

sudo apt-get update -y
sudo apt-get install -y nginx

sudo service nginx start

sudo sed -i '/^listen\s\+80;/c\listen 80;' /etc/nginx/sites-available/default

sudo kill -HUP "$(cat /var/run/nginx.pid)"

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
