#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 using round-robin algorithm

# Update package lists
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 303887-web-01:80 check
    server web-02 303887-web-02:80 check
EOL

# Enable HAProxy service to be managed via init script
sudo systemctl enable haproxy

# Restart HAProxy service to apply the changes
sudo systemctl restart haproxy
