#!/usr/bin/env bash
# Modifies Nginx config, checks status, restarts if needed, truncates pid file
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default; sudo sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default; sudo nginx -t >/dev/null 2>&1 || (echo "nginx is not running" && exit 1); sudo systemctl restart nginx && sudo truncate -s 0 /run/nginx.pid
