#!/usr/bin/env bash

# Function to remove PID file and exit
cleanup() {
  echo "Cleaning up and exiting..."
  rm -f /var/run/myscript.pid
  exit
}

# Create the PID file
echo $$ > /var/run/myscript.pid

# Set up trap signals
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT SIGTERM

# Display message
while true; do
  echo "To infinity and beyond"
  sleep 2
done
