#!/bin/bash

# Find the PID of the "7-highlander" process
pid=$(pgrep -o "7-highlander")

if [ -n "$pid" ]; then
  # If the process was found, terminate it gracefully
  echo "Stopping 7-highlander (PID: $pid)..."
  kill "$pid"
  echo "Process terminated."
else
  echo "7-highlander process not found."
fi
