#!/usr/bin/env bash
#prints a fizzbuzz game taking accounts multiples of 5 and 3
num=1

while [ $num -le 100 ]
do
        if [ $((num % 5)) -eq 0 ] && [ $((num % 3)) -eq 0 ]; then
                echo "FizzBuzz"

        elif [ $((num % 3)) -eq 0 ]; then
                echo "Fizz"

        elif [ $((num % 5)) -eq 0 ]; then
                echo "Buzz"

        else
                echo $num
        fi
        ((num++))
done
