#!/usr/bin/env bash
# Set the IFS to colon ":" to parse fields in /etc/passwd
IFS=":"

while read -r username password _ groupid userinfo homedir shell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $userinfo"
    echo
done < /etc/passwd

IFS=$' \t\n'

