#!/usr/bin/env bash
#Prints a string using while loop and if statement
count=1

while [ $count -le 10 ]
do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    ((count++))
done
