#!/usr/bin/env bash
#outputs a string using the case statement
num=1

while [ $num -le 20 ]
do
        case $num in
                "4")
                echo "4"
                echo "bad luck from china"
                ;;

                "9")
                echo "9"
                echo "bad luck from japan"
                ;;

                "17")
                echo "17"
                echo "bad luck from Italy"
		;;

                *)
                echo $num
                ;;
       esac

        ((num++))
done
