#!/usr/bin/env bash
#Outputs the hour and minutes
hour=0
minute=1

while [ $hour -le 12 ]; do
        printf "Hour: %d\n" $hour
        while [ $minute -le 59 ]; do
                printf "%d\n" $minute
                minute=$((minute + 1))
        done
        hour=$((hour + 1))
        minute=1
done
